# Generated by Django 3.0.7 on 2020-11-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201129_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='first_name',
            new_name='vorname',
        ),
    ]
