# Generated by Django 3.0.7 on 2020-11-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201129_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='last_name',
            new_name='familienname',
        ),
    ]
