# Generated by Django 3.0.7 on 2020-11-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201130_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='designation',
            new_name='beruf',
        ),
    ]
